export const UPLOAD_PRODUCT_OPEN_MODAL = 'UPLOAD_PRODUCT_OPEN_MODAL';
export const SET_AUTHEN_STATE = 'SET_AUTHEN_STATE';
export const SET_USER_ROLE = 'SET_USER_RULE';
export const PRODUCT_TABLE_DATA_CHANGED = 'PRODUCT_TABLE_DATA_CHANGED';
export const MODAL_DATA_CHANGED = 'MODAL_DATA_CHANGED';